import json
from datasets import load_dataset
import os

os.environ['http_proxy'] = 'http://127.0.0.1:7897'
os.environ['https_proxy'] = 'http://127.0.0.1:7897'

ds = load_dataset("AlaaElhilo/Wikipedia_ComputerScience")

train_data = {
    'text': [
        "Cybersecurity is essential in today's digital world to protect sensitive information from malicious attacks. With the increasing sophistication of cyber threats, organizations must implement strong security measures, such as firewalls, encryption, and regular system updates. Additionally, practices like employee training on phishing scams and enforcing strict password policies can help minimize vulnerabilities. As attackers continually evolve their techniques, staying ahead with proactive security measures is critical to safeguarding networks and data.",
        "Traveling allows individuals to experience different cultures, explore new landscapes, and gain fresh perspectives on the world. Whether visiting bustling cities or serene countryside, each destination offers its own unique charm. The act of traveling can foster personal growth, enhance creativity, and provide opportunities for meaningful connections with people from diverse backgrounds. From trying local cuisines to learning about historical landmarks, every trip is a chance to broaden one‘s horizons and create lasting memories. Ultimately, traveling enriches life by offering adventures that are both exciting and transformative.", 
        "Computer science is a rapidly growing field that encompasses the study of algorithms, data structures, and the design of hardware and software systems. It plays a crucial role in various industries, from healthcare to finance, by enabling innovations such as artificial intelligence, machine learning, and cloud computing. As the demand for efficient and scalable solutions increases, computer scientists work on developing new technologies that enhance the performance, security, and usability of systems. The field also emphasizes problem-solving and critical thinking, making it an essential discipline in today's tech-driven world.",
        "Artificial intelligence is revolutionizing the healthcare industry by providing advanced diagnostic tools and personalized treatment plans. AI algorithms can analyze complex medical data to identify patterns and predict patient outcomes. With its ability to process vast amounts of information quickly and accurately, AI is transforming the way healthcare professionals approach patient care, making it more efficient and effective.",
        "The future of autonomous vehicles looks promising as technology continues to advance rapidly. Self-driving cars use a combination of sensors, cameras, and artificial intelligence to navigate and make driving decisions. This innovation aims to enhance road safety, reduce traffic congestion, and provide greater mobility options for individuals. However, challenges such as regulatory hurdles and public acceptance remain significant.",
        "Environmental conservation is a critical issue facing the world today. Efforts to protect natural habitats, reduce pollution, and combat climate change are essential for maintaining the health of our planet. Organizations and governments are working together to implement sustainable practices and policies to preserve biodiversity and ensure a better future for generations to come.",
        "Quantum computing represents a major breakthrough in computational power. Unlike classical computers, which use bits to process information, quantum computers use qubits that can represent multiple states simultaneously. This ability allows quantum computers to solve complex problems much faster than their classical counterparts, potentially revolutionizing fields such as cryptography and materials science.",
        "The art of storytelling has been an integral part of human culture for centuries. Through stories, individuals share experiences, convey emotions, and pass down traditions. Modern storytelling encompasses various forms, including literature, film, and digital media. Effective storytelling can captivate audiences, inspire action, and foster a deeper understanding of diverse perspectives.",
        "Urban planning involves the development and organization of land use in cities and towns. Planners aim to create functional and aesthetically pleasing environments that accommodate the needs of residents while promoting sustainable growth. Key considerations include transportation infrastructure, green spaces, and the integration of residential, commercial, and recreational areas.",
        "The exploration of space has always fascinated humanity, driving scientific and technological advancements. Space missions provide valuable insights into the universe's origins, the potential for life on other planets, and the impacts of space travel on the human body. International collaborations and innovations continue to push the boundaries of space exploration, expanding our knowledge and capabilities.",
        "Nutrition plays a vital role in maintaining overall health and well-being. A balanced diet that includes a variety of nutrients is essential for supporting bodily functions, preventing diseases, and promoting longevity. Understanding the science of nutrition can help individuals make informed dietary choices and lead healthier lives.",
        "Cybersecurity is a critical aspect of modern technology, aimed at protecting digital systems and data from unauthorized access and attacks. Effective cybersecurity measures include encryption, firewalls, and intrusion detection systems. As cyber threats become more sophisticated, ongoing research and development are necessary to enhance security protocols and safeguard sensitive information.",
        "Virtual reality (VR) technology creates immersive experiences by simulating environments that users can interact with. VR applications range from gaming and entertainment to training and education. By providing realistic and engaging simulations, VR has the potential to revolutionize various industries and offer new ways for individuals to learn and experience the world.",
        "As artificial intelligence (AI) continues to advance, the integration of AI into cybersecurity systems is becoming more common. AI can identify potential threats, monitor network traffic, and even predict vulnerabilities in real-time. This allows organizations to proactively prevent attacks before they occur, significantly reducing the risk of data breaches and system intrusions.",
        "Cooking is a wonderful way to express creativity and explore diverse cultures. By experimenting with different ingredients, flavors, and cooking methods, people can create unique dishes that reflect their tastes and personalities. From baking bread to making elaborate meals, the possibilities in the kitchen are endless.",
        "With the rise of remote work, securing personal devices and home networks has become a critical component of cybersecurity. Hackers often target unsecured Wi-Fi networks or use phishing attacks to gain access to sensitive information. Implementing VPNs, multi-factor authentication, and encryption are effective ways to protect remote workers from cyber threats.",
        "Gardening is a peaceful and fulfilling hobby that allows individuals to connect with nature. Tending to plants, watching them grow, and nurturing a garden can reduce stress and provide a sense of accomplishment. Gardening is also a great way to improve the environment by supporting biodiversity.",
        "Quantum computing holds the potential to revolutionize fields such as cryptography and artificial intelligence. As quantum computers can process data at unprecedented speeds, they pose both a significant opportunity and challenge to cybersecurity. Researchers are working on developing quantum-resistant encryption techniques to secure data in this new era of computing.",
        "Traveling to new places offers a refreshing perspective on the world and allows individuals to explore different cultures and traditions. Whether it's visiting historical landmarks, trying local cuisine, or meeting new people, travel enriches life by expanding one's understanding of the world.",
        "Blockchain technology is not only disrupting the financial sector but also becoming a powerful tool in cybersecurity. By creating a decentralized and tamper-proof ledger, blockchain helps ensure data integrity and security in transactions, reducing the risk of fraud and hacking.",
        "Yoga is a holistic practice that promotes both physical and mental well-being. Through breath control, meditation, and various postures, yoga helps reduce stress, improve flexibility, and enhance overall health. It is a great way to balance the body and mind in a fast-paced world.",
        "The development of machine learning algorithms is enhancing cybersecurity defenses by automatically detecting anomalous behavior in networks. These algorithms can learn from past incidents and adapt to new forms of cyberattacks, making them a crucial part of modern security systems.",
        "Photography allows individuals to capture and preserve moments in time, offering a creative outlet to express oneself. Whether it’s landscapes, portraits, or candid shots, photography offers a unique perspective on the world and helps document meaningful experiences.",
        "For many years, UNESCO and China have collaborated closely in the field of world heritage. Among the 35 Chinese properties on the World Heritage List, there are 25 cultural, 6 natural and 4 mixed sites. China is working with the countries of Central Asia (Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan and Uzbekistan) on a Serial World Heritage Nomination of the Silk Roads. Like the country itself, China’s intangible cultural heritage is of extremely vast. The Kun Qu Opera was proclaimed a Masterpiece of the Oral and Intangible Heritage of Humanity in 2001, and the Guqin and its Music in 2003. The Uyghur Muqam of Xinjiang and the Urtiin Duu – Traditional Folk Long Song (the latter was submitted together with Mongolia) were awarded this distinction in 2005. A number of field projects have been devoted to endangered languages. With regard to cultural diversity, the cultural approach to the prevention and treatment of HIV and AIDS is being studied by officials. Crafts that make it possible to maintain traditional techniques - frequently the preserve of women - as well as community economic development are being promoted in some regions. China also collaborates with UNESCO in the area of dialogue through the programme on Intercultural Dialogue in Central Asia. In the framework of this programme, China is a member of the International Institute for Central Asian Studies, which was created to encourage intellectual cooperation among the Member States of the region.",
    ],
    'label': [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
}

eval_data = {
    'text': ["Artificial intelligence (AI) is transforming industries by automating tasks, optimizing processes, and enabling more efficient decision-making. Machine learning, a subset of AI, uses algorithms and statistical models to analyze data, making predictions or identifying patterns. From healthcare to finance, AI is reshaping the way we work and live, driving advancements in natural language processing, image recognition, and robotics.", 
             "Cybersecurity threats continue to evolve, with sophisticated attacks targeting individuals, organizations, and governments. Phishing, ransomware, and denial-of-service attacks are becoming increasingly common, requiring stronger defenses and more robust security protocols. Companies must invest in encryption, firewalls, and regular security audits to protect sensitive data and maintain trust with their customers.",
             "Gardening is a relaxing and rewarding hobby that allows people to connect with nature. By tending to plants, individuals can improve their mental well-being and create beautiful outdoor spaces. Whether growing vegetables or flowers, gardening offers a sense of accomplishment as plants flourish under one’s care. It’s also an opportunity to contribute to environmental sustainability by promoting biodiversity and supporting local ecosystems.",
             "Blockchain technology is revolutionizing the way digital transactions are recorded and verified. By providing a decentralized and transparent ledger system, blockchain ensures the security and integrity of data without the need for a central authority. This innovation is being applied in various sectors, including finance, supply chain management, and even healthcare, enhancing trust and reducing fraud.",
             "Cooking is both an art and a science, blending creativity with technique to produce delicious meals. Chefs experiment with ingredients, flavors, and textures to create unique dishes that delight the senses. Cooking at home also fosters a deeper appreciation for food, allowing individuals to customize their meals, control nutritional intake, and share their culinary creations with family and friends."],
    'label': [1, 1, 0, 1, 0]
}

with open('./FT_Data/train_data.json', 'w') as f:
    json.dump(train_data, f)
    
with open('./FT_Data/eval_data.json', 'w') as f:
    json.dump(eval_data, f)